name = "PyTinkerforge"
uuid = "7f8b0ca4-cb0e-484e-9ab2-c46751bbb33a"
authors = ["Jonas Schumacher <github735@jonasschumacher.de>"]
version = "2.1.30"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"

[compat]
Compat = "3"
DocStringExtensions = "0.8"
PyCall = "1"
Conda = "1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
